version: 2
updates:
  - package-eossystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  - package-eossystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"