name: build CI

on:
    push:
        branches: master
    workflow_dispatch:
    workflow_call:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest,ubuntu-latest,windows-latest,macos-13]
        runs-on: ${{matrix.os}}
        steps:
        - uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.8
            cache: 'pip' 
            cache-dependency-path: '**/requirements.txt'
        - name: Cache apt dependencies(for linux)
          uses: awalsh128/cache-apt-pkgs-action@latest 
          with: 
            packages: python-tk 
            execute_install_scripts: true
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Build
          run: pyinstaller -F --hidden-import=PIL._tkinter_finder --additional-hooks-dir=hooks main.py -n vcbot-bili -i .res/icon.ico
        - name: pack
          run: 7z a -tzip build-${{matrix.os}}.zip ./dist
        - name: Upload
          uses: actions/upload-artifact@v4
          with: 
            name: build-${{matrix.os}}
            path: ./build-${{matrix.os}}.zip